version: '3.8'
services:
  client-test:
    build: nginx-http
    container_name: client-test
    volumes:
      - .:/home/www
      - ./.env.test:/home/www/.env
    environment:
      - POOL_UID=${PHP_FPM_POOL_UID:-1000}
      - POOL_GID=${PHP_FPM_POOL_GID:-1000}
    ports:
      - 8001:80
