// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.3
// source: duat.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DocumentServiceClient is the client API for DocumentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentServiceClient interface {
	Store(ctx context.Context, in *DocumentRequest, opts ...grpc.CallOption) (*DocumentReply, error)
}

type documentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentServiceClient(cc grpc.ClientConnInterface) DocumentServiceClient {
	return &documentServiceClient{cc}
}

func (c *documentServiceClient) Store(ctx context.Context, in *DocumentRequest, opts ...grpc.CallOption) (*DocumentReply, error) {
	out := new(DocumentReply)
	err := c.cc.Invoke(ctx, "/duat.DocumentService/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentServiceServer is the server API for DocumentService service.
// All implementations must embed UnimplementedDocumentServiceServer
// for forward compatibility
type DocumentServiceServer interface {
	Store(context.Context, *DocumentRequest) (*DocumentReply, error)
	mustEmbedUnimplementedDocumentServiceServer()
}

// UnimplementedDocumentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDocumentServiceServer struct {
}

func (UnimplementedDocumentServiceServer) Store(context.Context, *DocumentRequest) (*DocumentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedDocumentServiceServer) mustEmbedUnimplementedDocumentServiceServer() {}

// UnsafeDocumentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentServiceServer will
// result in compilation errors.
type UnsafeDocumentServiceServer interface {
	mustEmbedUnimplementedDocumentServiceServer()
}

func RegisterDocumentServiceServer(s grpc.ServiceRegistrar, srv DocumentServiceServer) {
	s.RegisterService(&DocumentService_ServiceDesc, srv)
}

func _DocumentService_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/duat.DocumentService/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).Store(ctx, req.(*DocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocumentService_ServiceDesc is the grpc.ServiceDesc for DocumentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "duat.DocumentService",
	HandlerType: (*DocumentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _DocumentService_Store_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "duat.proto",
}

// DocumentImageServiceClient is the client API for DocumentImageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentImageServiceClient interface {
	Store(ctx context.Context, opts ...grpc.CallOption) (DocumentImageService_StoreClient, error)
}

type documentImageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentImageServiceClient(cc grpc.ClientConnInterface) DocumentImageServiceClient {
	return &documentImageServiceClient{cc}
}

func (c *documentImageServiceClient) Store(ctx context.Context, opts ...grpc.CallOption) (DocumentImageService_StoreClient, error) {
	stream, err := c.cc.NewStream(ctx, &DocumentImageService_ServiceDesc.Streams[0], "/duat.DocumentImageService/Store", opts...)
	if err != nil {
		return nil, err
	}
	x := &documentImageServiceStoreClient{stream}
	return x, nil
}

type DocumentImageService_StoreClient interface {
	Send(*DocumentImageRequest) error
	CloseAndRecv() (*DocumentImageReply, error)
	grpc.ClientStream
}

type documentImageServiceStoreClient struct {
	grpc.ClientStream
}

func (x *documentImageServiceStoreClient) Send(m *DocumentImageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *documentImageServiceStoreClient) CloseAndRecv() (*DocumentImageReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(DocumentImageReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DocumentImageServiceServer is the server API for DocumentImageService service.
// All implementations must embed UnimplementedDocumentImageServiceServer
// for forward compatibility
type DocumentImageServiceServer interface {
	Store(DocumentImageService_StoreServer) error
	mustEmbedUnimplementedDocumentImageServiceServer()
}

// UnimplementedDocumentImageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDocumentImageServiceServer struct {
}

func (UnimplementedDocumentImageServiceServer) Store(DocumentImageService_StoreServer) error {
	return status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedDocumentImageServiceServer) mustEmbedUnimplementedDocumentImageServiceServer() {}

// UnsafeDocumentImageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentImageServiceServer will
// result in compilation errors.
type UnsafeDocumentImageServiceServer interface {
	mustEmbedUnimplementedDocumentImageServiceServer()
}

func RegisterDocumentImageServiceServer(s grpc.ServiceRegistrar, srv DocumentImageServiceServer) {
	s.RegisterService(&DocumentImageService_ServiceDesc, srv)
}

func _DocumentImageService_Store_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DocumentImageServiceServer).Store(&documentImageServiceStoreServer{stream})
}

type DocumentImageService_StoreServer interface {
	SendAndClose(*DocumentImageReply) error
	Recv() (*DocumentImageRequest, error)
	grpc.ServerStream
}

type documentImageServiceStoreServer struct {
	grpc.ServerStream
}

func (x *documentImageServiceStoreServer) SendAndClose(m *DocumentImageReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *documentImageServiceStoreServer) Recv() (*DocumentImageRequest, error) {
	m := new(DocumentImageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DocumentImageService_ServiceDesc is the grpc.ServiceDesc for DocumentImageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentImageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "duat.DocumentImageService",
	HandlerType: (*DocumentImageServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Store",
			Handler:       _DocumentImageService_Store_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "duat.proto",
}

// DepartmentServiceClient is the client API for DepartmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DepartmentServiceClient interface {
	All(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*DepartmentListReply, error)
	Store(ctx context.Context, in *DepartmentRequest, opts ...grpc.CallOption) (*DepartmentReply, error)
}

type departmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDepartmentServiceClient(cc grpc.ClientConnInterface) DepartmentServiceClient {
	return &departmentServiceClient{cc}
}

func (c *departmentServiceClient) All(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*DepartmentListReply, error) {
	out := new(DepartmentListReply)
	err := c.cc.Invoke(ctx, "/duat.DepartmentService/All", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departmentServiceClient) Store(ctx context.Context, in *DepartmentRequest, opts ...grpc.CallOption) (*DepartmentReply, error) {
	out := new(DepartmentReply)
	err := c.cc.Invoke(ctx, "/duat.DepartmentService/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DepartmentServiceServer is the server API for DepartmentService service.
// All implementations must embed UnimplementedDepartmentServiceServer
// for forward compatibility
type DepartmentServiceServer interface {
	All(context.Context, *EmptyRequest) (*DepartmentListReply, error)
	Store(context.Context, *DepartmentRequest) (*DepartmentReply, error)
	mustEmbedUnimplementedDepartmentServiceServer()
}

// UnimplementedDepartmentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDepartmentServiceServer struct {
}

func (UnimplementedDepartmentServiceServer) All(context.Context, *EmptyRequest) (*DepartmentListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method All not implemented")
}
func (UnimplementedDepartmentServiceServer) Store(context.Context, *DepartmentRequest) (*DepartmentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedDepartmentServiceServer) mustEmbedUnimplementedDepartmentServiceServer() {}

// UnsafeDepartmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DepartmentServiceServer will
// result in compilation errors.
type UnsafeDepartmentServiceServer interface {
	mustEmbedUnimplementedDepartmentServiceServer()
}

func RegisterDepartmentServiceServer(s grpc.ServiceRegistrar, srv DepartmentServiceServer) {
	s.RegisterService(&DepartmentService_ServiceDesc, srv)
}

func _DepartmentService_All_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartmentServiceServer).All(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/duat.DepartmentService/All",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartmentServiceServer).All(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepartmentService_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepartmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartmentServiceServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/duat.DepartmentService/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartmentServiceServer).Store(ctx, req.(*DepartmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DepartmentService_ServiceDesc is the grpc.ServiceDesc for DepartmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DepartmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "duat.DepartmentService",
	HandlerType: (*DepartmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "All",
			Handler:    _DepartmentService_All_Handler,
		},
		{
			MethodName: "Store",
			Handler:    _DepartmentService_Store_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "duat.proto",
}

// DocumentTypeServiceClient is the client API for DocumentTypeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentTypeServiceClient interface {
	All(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*DocumentTypeListReply, error)
	Store(ctx context.Context, in *DocumentTypeRequest, opts ...grpc.CallOption) (*DocumentTypeReply, error)
}

type documentTypeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentTypeServiceClient(cc grpc.ClientConnInterface) DocumentTypeServiceClient {
	return &documentTypeServiceClient{cc}
}

func (c *documentTypeServiceClient) All(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*DocumentTypeListReply, error) {
	out := new(DocumentTypeListReply)
	err := c.cc.Invoke(ctx, "/duat.DocumentTypeService/All", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentTypeServiceClient) Store(ctx context.Context, in *DocumentTypeRequest, opts ...grpc.CallOption) (*DocumentTypeReply, error) {
	out := new(DocumentTypeReply)
	err := c.cc.Invoke(ctx, "/duat.DocumentTypeService/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentTypeServiceServer is the server API for DocumentTypeService service.
// All implementations must embed UnimplementedDocumentTypeServiceServer
// for forward compatibility
type DocumentTypeServiceServer interface {
	All(context.Context, *EmptyRequest) (*DocumentTypeListReply, error)
	Store(context.Context, *DocumentTypeRequest) (*DocumentTypeReply, error)
	mustEmbedUnimplementedDocumentTypeServiceServer()
}

// UnimplementedDocumentTypeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDocumentTypeServiceServer struct {
}

func (UnimplementedDocumentTypeServiceServer) All(context.Context, *EmptyRequest) (*DocumentTypeListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method All not implemented")
}
func (UnimplementedDocumentTypeServiceServer) Store(context.Context, *DocumentTypeRequest) (*DocumentTypeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedDocumentTypeServiceServer) mustEmbedUnimplementedDocumentTypeServiceServer() {}

// UnsafeDocumentTypeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentTypeServiceServer will
// result in compilation errors.
type UnsafeDocumentTypeServiceServer interface {
	mustEmbedUnimplementedDocumentTypeServiceServer()
}

func RegisterDocumentTypeServiceServer(s grpc.ServiceRegistrar, srv DocumentTypeServiceServer) {
	s.RegisterService(&DocumentTypeService_ServiceDesc, srv)
}

func _DocumentTypeService_All_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentTypeServiceServer).All(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/duat.DocumentTypeService/All",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentTypeServiceServer).All(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentTypeService_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentTypeServiceServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/duat.DocumentTypeService/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentTypeServiceServer).Store(ctx, req.(*DocumentTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocumentTypeService_ServiceDesc is the grpc.ServiceDesc for DocumentTypeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentTypeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "duat.DocumentTypeService",
	HandlerType: (*DocumentTypeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "All",
			Handler:    _DocumentTypeService_All_Handler,
		},
		{
			MethodName: "Store",
			Handler:    _DocumentTypeService_Store_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "duat.proto",
}
