name: ged-client-image-publish
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker Hub Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build php-cli image
        uses: docker/build-push-action@v5
        with:
          context: '.'
          target: 'cli'
          push: true
          tags: |
            devoptimus/ged-client-cli:latest

      - name: Build fpm image
        uses: docker/build-push-action@v5
        with:
          context: '.'
          target: 'fpm'
          push: true
          tags: |
            devoptimus/ged-client-fpm:latest

      - name: Build nginx image
        uses: docker/build-push-action@v5
        with:
          context: '.'
          target: 'nginx'
          push: true
          tags: |
            devoptimus/ged-client-nginx:latest

      - name: Build grpc-server image
        uses: docker/build-push-action@v5
        with:
          context: '.'
          target: 'grpc'
          push: true
          tags: |
            devoptimus/ged-client-grpc-server:latest
